theme: jekyll-theme-slate
title: "Gustavo Leão, meus Posts",
description: "Este é o um projeto com meus trabalhos e exercícos de programação.",
show_downloads: true
---
layout: default
comments: true
# other options
--- 
