theme: jekyll-theme-time-machine
<<<<<<< HEAD
title: "Gustavo Leão, meus Posts"
description: "Este é o um projeto com meus trabalhos e exercícos de programação."
=======
title: "Gustavo Leão, meus Posts",
description: "Este é o um projeto com meus trabalhos e exercícos de programação.",
>>>>>>> d00f0d130cf98000a861f58fc1a0f48e068660ff
show_downloads: true
